[package]
name = "CVE-2023-46818"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "form"] }
tokio = { version = "1.0", features = ["full"] }
base64 = "0.21"
rand = "0.8"
regex = "1.0"
url = "2.4"
serde_json = "1.0"
